JVMCBC-1452: Runtime failure due to 'java.lang.NoClassDefFoundError: io/opentelemetry/instrumentation/api/instrumenter/SpanNameExtractor'
Bumping Java FIT performer to include this fix.

And bumping the Opentelemetry library version so it's
compatible with current tracing-opentelemetry.

Change-Id: I47905898cc7f6d213503b15f9a1ce3346f5e844e
Reviewed-on: https://review.couchbase.org/c/couchbase-jvm-clients/+/202503
Reviewed-by: Graham Pople <graham.pople@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>