Tests - marking allowsToConfigureCustomCipher @Flaky
This test has gone through many iterations, with no success
in finding a cipher that reliably works across all tested
JDKs.  The latest problem, going back to the original TLS_AES_256_GCM_SHA384
since the logic to choose a cipher from the supported list
at runtime did not pan out due to various SSL errors from various
JDKs, is this error from Oracle JDK 11:

SSLHandshakeException: Received fatal alert: protocol_version

At this point it's an unrealistic level of effort for a single
test of tertiary functionality, and is blocking the more important
need to get the tests to consistent green - temporarily disabling.

Change-Id: I232e574510699640692e4c23dddb93f11f4cafae
Reviewed-on: https://review.couchbase.org/c/couchbase-jvm-clients/+/183271
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: David Nault <david.nault@couchbase.com>