JVMCBC-1452: Runtime failure due to 'java.lang.NoClassDefFoundError: io/opentelemetry/instrumentation/api/instrumenter/SpanNameExtractor'
Applications trying to use the tracing-opentelemetry module
are failing at runtime with this SpanNameExtractor error.

Fixing by having tracing-opentelemetry-deps include all its
dependencies.

tracing-opentelemetry-deps is fully shaded into
tracing-opentelemetry so there is no user impact.

The tracing-opentelemetry jar goes from 50kb to 615kb.

Change-Id: I6343c1c513e3d7d4bb94f3280bb70b52414289cb
Reviewed-on: https://review.couchbase.org/c/couchbase-jvm-clients/+/202501
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Michael Reiche <michael.reiche@couchbase.com>